---
# tasks file for ansible-role-solr-prometheus-exporter

- name: Solr_prometheus | Copy service template
  template:
    src: prometheus_solr_exporter.service.j2
    dest: /etc/systemd/system/prometheus_solr_exporter.service
    owner: root
    group: root
    mode: 0644
  tags:
    - prometheus_solr_exporter_service

- name: Solr_prometheus | Enabling service
  systemd:
    name: prometheus_solr_exporter
    state: started
    enabled: true
    daemon_reload: true
  tags:
    - prometheus_solr_exporter_service
