---
# ------------------------------------------------------------------------
- name: Prepare Install role dependencies
  hosts: all
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  vars:
    # - solr_install_path: /opt/solr
  roles:
    - contrib/geerlingguy.java
    - contrib/geerlingguy.solr

# ------------------------------------------------------------------------
- name: Prepare targets for converge
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

    - name: Update yum
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'


